platform :ios, '13.0'

target 'Messenger' do
  use_frameworks!

  # Architecture
  pod 'ReactorKit', '2.1.0'
  
  # Rx
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxDataSources'
  pod 'RxOptional', '4.1.0'
  pod 'RxGesture', :git => 'https://github.com/martinolee/RxGesture.git', :commit => '52c61481973f15ef8f2042eb5cdc08edd6c791f6' # 3.0.2
  
  # UI
  pod 'SnapKit', '5.0.1'
  
  # Networking
  pod 'Alamofire', '5.1.0'
  pod 'Kingfisher', :git => 'https://github.com/martinolee/Kingfisher.git', :commit => '6685e09197bc90b3268d70aab0ccfb49e2fcf1dc' # 5.14.0
  
  # Database
  pod 'RealmSwift', '5.0.0'
  
  # Firebase
  pod 'Firebase/Analytics', '6.23.0'
  pod 'Firebase/Auth', '6.23.0'
  pod 'Firebase/Core', '6.23.0'
  pod 'Firebase/Firestore', '6.23.0'
  
  # Debug
  pod 'Gedatsu', configuration: %w(Debug)
  
  # Misc
  pod 'SwiftLint', '0.39.2'
  pod 'Then', '2.6.0'

end
